apiVersion: v1
kind: PersistentVolume
metadata:
  name: stack-io-logs-pv
  namespace: stack-io
  labels:
    app: stack-io
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stack-io-logs-pvc
  labels:
    app: stack-io
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
