apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stack-io

resources:
  - namespace.yaml
  - rbac.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - pvc.yaml
  - network-policy.yaml

secretGenerator:
- name: stack-io-db-secret
  files:
  - ./config/server.confi

configMapGenerator:
- name: stack-io-hooks-configmap
  files:
  - ./config/hooks/pre-stop-hook.sh
  - ./config/hooks/post-start-hook.sh
- name: stack-io-scripts-configmap
  files:
  - ./config/scripts/init-setup.sh

configurations:
  - kustomizeconfig.yaml
