test: ENC[AES256_GCM,data:Nyb/fQ==,iv:oeWpCaEZwE99qEJXT0s6ftAE2XKJ8ivjQ/a1qFBQWv0=,tag:4FYycrWuk7igc50E2BFfbQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age170kjjr9j3y2yl7etp9h7eknp9x4pxwujzvdj95k7j4xxxdags3ssdd4pdk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3dnhCTVZDYW4vcHJaKzB2
            bERoWWdnbUc4anc4dndjdjY3MXBTV0hua2tRCmFtQktKK3RmVERjbVgwQUpxZVdi
            cmtCTUg4L2FPQlJJUHduQ2FkZXBqMXcKLS0tIC92ZElMOHFCZytKclBBVXBoS2o3
            bTVSRWtVQTlPc1V1MVBWQTNzWGRjWHMK0ploa0weezXauTZ5sRnZXjh3LDZgWxgq
            FJuAjP9X2MhufUNEnSbcAJX3Z3RVB1FdJNUeYVJDo/rJjCPZTGbhig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-07T01:45:21Z"
    mac: ENC[AES256_GCM,data:cmZm/oyQkEp9zxmz4adX4rddsfftpTxRvtvP+xv4gIhBt31fUZGUl08erDdlDoCiJNTT3oxQ5ajJXYUJt27qwmc/06GUotI8NCn/uzr6as3fgjdo2UWq+n4VJqxafOOITzsJqxwB0aY+7GNFhu6QtVylb1jgzBgRWsh1SliaF/Y=,iv:Hw0C25VXOG4Jk2WhvQbUutjg4enaZukdSrA+khu712k=,tag:GyEXnYCwHIAa3vsX72zBLQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
