apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mysql

resources:
  - namespace.yaml
  - pv.yaml
  - deployment.yaml
  - service.yaml

secretGenerator:
- name: mysql-secret
  envs:
  - ./config/.env.secret

configMapGenerator:
- name: mysql-init-configmap
  files:
  - ./config/mysql-init.sh

configurations:
  - kustomizeconfig.yaml

generatorOptions:
  disableNameSuffixHash: false