nameReference:
    - kind: ConfigMap
      version: v1
      fieldSpecs:
        - kind: Deployment
          path: spec/template/spec/volumes[]/configMap/name
        - kind: Deployment
          path: spec/template/spec/containers[0]/envFrom[0]/configMapRef/name
        - kind: StatefulSet
          path: spec/template/spec/volumes[]/configMap/name
        - kind: StatefulSet
          path: spec/template/spec/containers[0]/envFrom[0]/configMapRef/name
    - kind: Secret
      version: v1
      fieldSpecs:
        - kind: Deployment
          path: spec/template/spec/volumes[]/secret/secretName
        - kind: Deployment
          path: spec/template/spec/containers[0]/envFrom[0]/secretRef/name
        - kind: StatefulSet
          path: spec/template/spec/volumes[]/secret/secretName
        - kind: StatefulSet
          path: spec/template/spec/containers[0]/envFrom[0]/secretRef/name